In [11]:
import spacy
import numpy as np
import pandas as pd
import nltk
import re
from transformers import pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from PyPDF2 import PdfReader
from langchain.text_splitter import CharacterTextSplitter

In [12]:
nlp = spacy.load('en_core_web_sm')
read=PdfReader(r"C:\Users\sarthak mohapatra\Downloads\P2- UQ.pdf")


In [13]:
raw_text=''
for page_num in range(len(read.pages)):
        page = read.pages[page_num]
        content = page.extract_text()
        raw_text += content

In [14]:
text_splitter = CharacterTextSplitter(
    separator = "\n",
    chunk_size = 400,
    chunk_overlap  = 200,
    length_function = len,
)
texts = text_splitter.split_text(raw_text)
for text_chunk in range(len(texts)):
    print(texts[text_chunk])

/gid00030/gid00035/gid00032/gid00030/gid00038/gid00001/gid00033/gid00042/gid00045 /gid00001
/gid00048/gid00043/gid00031/gid00028/gid00047/gid00032/gid00046Citation: Barandas, M.; Folgado, D.;
Santos, R.; Simão, R.; Gamboa, H.
Uncertainty-Based Rejection in Machine
Learning: Implications for Model
Development and Interpretability.
Electronics 2022 ,11, 396. https://
Santos, R.; Simão, R.; Gamboa, H.
Uncertainty-Based Rejection in Machine
Learning: Implications for Model
Development and Interpretability.
Electronics 2022 ,11, 396. https://
doi.org/10.3390/electronics11030396
Academic Editors: Christian
Morbidoni, Francesco Di Nardo and
Alessandro Cucchiarelli
Received: 20 December 2021
Accepted: 26 January 2022
Published: 28 January 2022
Academic Editors: Christian
Morbidoni, Francesco Di Nardo and
Alessandro Cucchiarelli
Received: 20 December 2021
Accepted: 26 January 2022
Published: 28 January 2022
Publisher’s Note: MDPI stays neutral
with regard to jurisdictional claims in
published m

In [15]:
def ex_summary(text,numsent):
    doc=nlp(text)
    sentences = [sent.text for sent in doc.sents]
    vector= TfidfVectorizer()
    top=vector.fit_transform(sentences)
    sentence_scores = np.sum(top.toarray(), axis=1)
    print(sentence_scores)
    summary = [sentences[i] for i in sentence_scores.argsort()[-numsent:][::-1]]
    return ' ' .join(summary)


In [16]:
sample="""Artificial intelligence (AI) is a rapidly evolving field that aims to create systems capable of performing tasks that typically require human intelligence. These tasks include learning, reasoning, problem-solving, perception, and language understanding. AI technologies are driven by advances in machine learning, deep learning, and neural networks, enabling computers to learn from data and improve over time. AI applications span various sectors, including healthcare, finance, transportation, and entertainment.

In healthcare, AI assists in diagnosing diseases, personalizing treatment plans, and predicting patient outcomes. Financial institutions leverage AI for fraud detection, risk assessment, and algorithmic trading. Autonomous vehicles rely on AI to navigate and make real-time decisions. In the realm of entertainment, AI powers recommendation engines for platforms like Netflix and Spotify.

Despite its potential, AI also raises ethical concerns. Issues such as data privacy, algorithmic bias, and job displacement need to be addressed to ensure responsible AI development and deployment. Researchers and policymakers are working on frameworks to balance innovation with ethical considerations.

AI continues to transform industries and improve daily life, making it a crucial area of study and development. As AI systems become more sophisticated, they hold the promise of solving complex problems and creating new opportunities, fundamentally changing how we interact with technology and the world around us."""

In [17]:
[e_summary(text_chunk,5) for text_chunk in texts]

[5.37587202 2.         1.        ]
[3.86744535 1.97099145 4.87787798 1.96891082]
[4.33966858 4.45098551 1.         1.97948731 1.99337319 2.33333333]
[3.45969238 1.         1.99029143 2.         4.69717179 1.40734857]
[3.94418506 4.88216518]
[3.7237493  3.65847957]
[4.89897949]
[5.66996389 3.5911305  1.        ]
[3.43387572 4.32698421 4.04147202]
[3.5124581  5.00710209 3.80855593]
[3.54317925 4.4223345  3.40970754 2.40307647 1.40619668]
[2.23606798 3.44780345 2.4379652  4.68850912 2.22887766]
[4.43305306 3.42373543 3.5602457 ]
[3.58435139 4.45808457]
[0.         4.59733174 4.31783023 2.44134811]
[4.28618575 3.35821314 2.98287383 3.13041704]
[2.61463224 2.97390196 4.54190491 3.96153893]
[3.24582056 4.29993062 4.9532357 ]
[1.72216301 4.97478862 4.28678034 1.70362687]
[1.38095532 4.28611099 3.73870295 3.4327805 ]
[3.37765892 3.58782502 3.81537526 2.40470597]
[1.         3.77649191 4.20932471 3.70836287]
[3.42059198 4.48065173 1.69360614]
[4.51739547 2.62116157 3.855384  ]
[1.98421271 5.948

['/gid00030/gid00035/gid00032/gid00030/gid00038/gid00001/gid00033/gid00042/gid00045 /gid00001\n/gid00048/gid00043/gid00031/gid00028/gid00047/gid00032/gid00046Citation: Barandas, M.; Folgado, D.;\nSantos, R.; Simão, R.; Gamboa, H.\nUncertainty-Based Rejection in Machine\nLearning: Implications for Model\nDevelopment and Interpretability.\n Electronics 2022 ,11, 396. https://',
 'https://\ndoi.org/10.3390/electronics11030396\nAcademic Editors: Christian\nMorbidoni, Francesco Di Nardo and\nAlessandro Cucchiarelli\nReceived: 20 December 2021\nAccepted: 26 January 2022\n Santos, R.; Simão, R.; Gamboa, H.\nUncertainty-Based Rejection in Machine\nLearning: Implications for Model\nDevelopment and Interpretability.\n Electronics 2022 ,11, 396. Published: 28 January 2022',
 '28 January 2022\nPublisher’s Note: MDPI stays neutral\nwith regard to jurisdictional claims in\npublished maps and institutional affil-\niations.\n Academic Editors: Christian\nMorbidoni, Francesco Di Nardo and\nAlessandro Cu

In [18]:
import spacy
import numpy as np
from gensim.models import Word2Vec, KeyedVectors
from nltk.tokenize import sent_tokenize, word_tokenize


nlp = spacy.load("en_core_web_sm")


model = Word2Vec(sample, vector_size=100, window=5, min_count=1, workers=4)

def sentence_vector(sentence, model):
    words = word_tokenize(sentence)
    word_vecs = [model.wv[word] for word in words if word in model.wv]
    if not word_vecs:
        return np.zeros(model.vector_size)
    return np.mean(word_vecs, axis=0)

def document_vector(document, model):
    words = word_tokenize(document)
    word_vecs = [model.wv[word] for word in words if word in model.wv]
    if not word_vecs:
        return np.zeros(model.vector_size)
    return np.mean(word_vecs, axis=0)

def e_summary(text, numsent):
    doc = nlp(text)
    sentences = [sent.text for sent in doc.sents]
    
   
    doc_vec = document_vector(text, model)
    
    
    sentence_scores = []
    for sent in sentences:
        sent_vec = sentence_vector(sent, model)
        similarity = np.dot(doc_vec, sent_vec) / (np.linalg.norm(doc_vec) * np.linalg.norm(sent_vec))
        sentence_scores.append(similarity)
    
   
    print("Sentence scores:", sentence_scores)
    

    top_sentence_indices = np.argsort(sentence_scores)[-numsent:][::-1]
    
 
    summary = [sentences[i] for i in top_sentence_indices]
    
    return '\n'.join(summary)


num_sentences = 10

summary = [e_summary(text_chunk, num_sentences) for text_chunk in texts]
print("Summary:", summary)

C:\Users\sarthak mohapatra\AppData\Local\Temp\ipykernel_7148\2494437653.py:37: RuntimeWarning: invalid value encountered in scalar divide
  similarity = np.dot(doc_vec, sent_vec) / (np.linalg.norm(doc_vec) * np.linalg.norm(sent_vec))


Sentence scores: [0.99947023, 0.80939084, nan]
Sentence scores: [0.99211246, 0.82807434, 0.9802796, nan]
Sentence scores: [0.67325246, 0.6103508, nan, 0.69972456, 0.9201282, nan]
Sentence scores: [0.7820894, nan, 0.7820894, 0.6594528, 0.7422658, nan]
Sentence scores: [0.5454428, 0.79852057]
Sentence scores: [0.79786557, 0.9068147]
Sentence scores: [0.99999994]
Sentence scores: [0.9770924, 0.87155986, nan]
Sentence scores: [0.89672434, 0.92039704, 0.76441383]
Sentence scores: [0.7820894, 0.79997367, 0.5034795]
Sentence scores: [0.22614604, 0.9422839, 0.9422839, 0.85001063, nan]
Sentence scores: [0.6488466, 0.96481526, 0.7002124, 0.93999326, nan]
Sentence scores: [0.9546417, 0.6629174, nan]
Sentence scores: [0.7820894, 0.9444478]
Sentence scores: [0.79193854, 0.90538454, 0.9132318, nan]
Sentence scores: [0.98018295, 0.8315373, 0.8315373, 0.54578584]
Sentence scores: [0.7992118, 0.7992118, 0.840493, 0.28111786]
Sentence scores: [0.7426404, 0.8022276, 0.91748565]
Sentence scores: [0.566777

In [19]:
summarizer=pipeline(task="summarisation",model="facebook/bart-large-cnn")
def a_summary(text,max_length,min_length):
  input_length = len(text)
  default_max_length=max_length
  max_length = min(default_max_length, input_length // 2)
  min_length = min(min_length, max_length - 1)
  print(f"Input length: {input_length}")
  print(f"Max length set to: {max_length}")
  print(f"Min length set to: {min_length}")
  nlp=summarizer(text,max_length=max_length,min_length=min_length,do_sample=False)
  return nlp[0]


In [21]:
[a_summary(text,50,20) for text in texts]

Input length: 367
Max length set to: 50
Min length set to: 20
Input length: 377
Max length set to: 50
Min length set to: 20
Input length: 398
Max length set to: 50
Min length set to: 20
Input length: 360
Max length set to: 50
Min length set to: 20
Input length: 366
Max length set to: 50
Min length set to: 20
Input length: 341
Max length set to: 50
Min length set to: 20
Input length: 388
Max length set to: 50
Min length set to: 20
Input length: 394
Max length set to: 50
Min length set to: 20
Input length: 395
Max length set to: 50
Min length set to: 20
Input length: 388
Max length set to: 50
Min length set to: 20
Input length: 385
Max length set to: 50
Min length set to: 20
Input length: 381
Max length set to: 50
Min length set to: 20
Input length: 398
Max length set to: 50
Min length set to: 20
Input length: 327
Max length set to: 50
Min length set to: 20
Input length: 362
Max length set to: 50
Min length set to: 20
Input length: 350
Max length set to: 50
Min length set to: 20
Input le

[{'summary_text': 'Citation: Barandas, M., Folgado, D., Santos, R., Simão, R.; Gamboa, H. Uncertainty-Based Rejection in MachineLearning: Implications for ModelDevelopment and Interpret'},
 {'summary_text': 'Uncertainty-Based Rejection in Machine.Learning: Implications for ModelDevelopment and Interpretability.'},
 {'summary_text': 'This article is an open access article. Use this article to help people with reading comprehension and vocabulary. Use the weekly Newsquiz to test your knowledge of stories you saw in this article.'},
 {'summary_text': 'This article is an open access articledistributed under the terms and conditions of the Creative CommonsAttribution (CC BY) license. The author is responsible for the publication of this article.'},
 {'summary_text': 'Uncertainty-Based Rejection in Machine Learning: Implications for Model Development and Interpretability. distributed under the terms and conditions of the Creative CommonsAttribution (CC BY) license.'},
 {'summary_text': 'Asso

In [32]:
from flask import Flask, request, jsonify, render_template
from werkzeug.utils import secure_filename
import os
import spacy
import numpy as np
from PyPDF2 import PdfReader
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import pipeline
from langchain.text_splitter import CharacterTextSplitter

# Initialize Flask app
app = Flask(__name__)

# Set the upload folder
UPLOAD_FOLDER = 'uploads/'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# Ensure the upload folder exists
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

# Load models
nlp = spacy.load('en_core_web_sm')
summarizer = pipeline(task="summarization", model="facebook/bart-large-cnn")

# Define summarization functions
def e_summary(text, numsent):
    doc = nlp(text)
    sentences = [sent.text for sent in doc.sents]
    vector = TfidfVectorizer()
    top = vector.fit_transform(sentences)
    sentence_scores = np.sum(top.toarray(), axis=1)
    summary = [sentences[i] for i in sentence_scores.argsort()[-numsent:][::-1]]
    return ' '.join(summary)

def a_summary(text, max_length, min_length):
    input_length = len(text)
    default_max_length = max_length
    max_length = min(default_max_length, input_length // 2)
    min_length = min(min_length, max_length - 1)
    nlp_result = summarizer(text, max_length=max_length, min_length=min_length, do_sample=False)
    return nlp_result[0]['summary_text']

@app.route('/')
def index():
    return render_template('indexnlp.html')

@app.route('/summarize', methods=['POST'])
def summarize():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'})

    file = request.files['file']
    
    if file.filename == '':
        return jsonify({'error': 'No selected file'})

    summary_type = request.form.get('summary_type')

    if file:
        filename = secure_filename(file.filename)
        file_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        file.save(file_path)

   
        raw_text = ''
        if file_path.endswith('.txt'):
            with open(file_path, 'r') as f:
                raw_text = f.read()
        elif file_path.endswith('.pdf'):
            reader = PdfReader(file_path)
            for page_num in range(len(reader.pages)):
                page = reader.pages[page_num]
                raw_text += page.extract_text()
        else:
            return jsonify({'error': 'Unsupported file format'})

       
        text_splitter = CharacterTextSplitter(
            separator="\n",
            chunk_size=400,
            chunk_overlap=200,
            length_function=len,
        )
        texts = text_splitter.split_text(raw_text)

   
        if summary_type == 'extractive':
            summaries = [e_summary(text, 3) for text in texts]  
        elif summary_type == 'abstractive':
            summaries = [a_summary(text, max_length=50, min_length=20) for text in texts]  
        else:
            return jsonify({'error': 'Invalid summary type selected'})

        result = ' '.join(summaries)

        return render_template('indexnlp.html', result=result)

    return jsonify({'error': 'File upload failed'})

if __name__ == '__main__':
    app.run()


 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [17/Jul/2024 21:19:04] "GET / HTTP/1.1" 200 -
Your max_length is set to 50, but your input_length is only 49. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=24)
127.0.0.1 - - [17/Jul/2024 21:20:55] "POST /summarize HTTP/1.1" 200 -


In [2]:
from flask import Flask, request, jsonify, render_template
from werkzeug.utils import secure_filename
import os
import spacy
import numpy as np
from PyPDF2 import PdfReader
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import pipeline
from langchain.text_splitter import CharacterTextSplitter


app = Flask(__name__)


UPLOAD_FOLDER = 'uploads/'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER


if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)


nlp = spacy.load('en_core_web_sm')
summarizer = pipeline(task="summarization", model="facebook/bart-large-cnn")


def e_summary(text, numsent):
    doc = nlp(text)
    sentences = [sent.text for sent in doc.sents]
    vector = TfidfVectorizer()
    top = vector.fit_transform(sentences)
    sentence_scores = np.sum(top.toarray(), axis=1)
    summary = [sentences[i] for i in sentence_scores.argsort()[-numsent:][::-1]]
    return ' '.join(summary)

def a_summary(text, max_length, min_length):
    input_length = len(text)
    default_max_length = max_length
    max_length = min(default_max_length, input_length // 2)
    min_length = min(min_length, max_length - 1)
    nlp_result = summarizer(text, max_length=max_length, min_length=min_length, do_sample=False)
    return nlp_result[0]['summary_text']

@app.route('/')
def index():
    return render_template('indexnlp.html')

@app.route('/summarize_file', methods=['POST'])
def summarize_file():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'})

    file = request.files['file']
    
    if file.filename == '':
        return jsonify({'error': 'No selected file'})

    summary_type = request.form.get('summary_type')

    if file:
        filename = secure_filename(file.filename)
        file_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        file.save(file_path)

       
        raw_text = ''
        if file_path.endswith('.txt'):
            with open(file_path, 'r') as f:
                raw_text = f.read()
        elif file_path.endswith('.pdf'):
            reader = PdfReader(file_path)
            for page_num in range(len(reader.pages)):
                page = reader.pages[page_num]
                raw_text += page.extract_text()
        else:
            return jsonify({'error': 'Unsupported file format'})

      
        text_splitter = CharacterTextSplitter(
            separator="\n",
            chunk_size=400,
            chunk_overlap=200,
            length_function=len,
        )
        texts = text_splitter.split_text(raw_text)

    
        if summary_type == 'extractive':
            summaries = [e_summary(text, 3) for text in texts] 
        elif summary_type == 'abstractive':
            summaries = [a_summary(text, max_length=130, min_length=30) for text in texts]  
        else:
            return jsonify({'error': 'Invalid summary type selected'})

        result_file = ' '.join(summaries)

        return render_template('indexnlp.html', result_file=result_file)

    return jsonify({'error': 'File upload failed'})

@app.route('/summarize_text', methods=['POST'])
def summarize_text():
    text = request.form.get('text')
    summary_type = request.form.get('summary_type')

    if not text:
        return jsonify({'error': 'No text provided'})

   
    if summary_type == 'extractive':
        result_text = e_summary(text, 3)  
    elif summary_type == 'abstractive':
        result_text = a_summary(text, max_length=130, min_length=30) 
    else:
        return jsonify({'error': 'Invalid summary type selected'})

    return render_template('indexnlp.html', result_text=result_text)

if __name__ == '__main__':
    app.run()


 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [18/Jul/2024 09:55:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Jul/2024 09:55:49] "POST /summarize_text HTTP/1.1" 200 -
127.0.0.1 - - [18/Jul/2024 09:56:08] "POST /summarize_text HTTP/1.1" 200 -
